### ISSUE TITLE
DiffKit as a copy instead of a dependency?

### ISSUE THREAD

**Issue by kgn** [riteshhgupta/RGListKit#1]
This project looks like exactly what I was looking for! I have a question about DiffKit, it appears the code is copied into this project instead of included as a dependency?

**Comment by riteshhgupta** [comment]
Hey @kgn, Dwifft was added a lot later into the project so I had to make RGListKit's data structure work with Dwifft's data structure which needed some changes in Dwifft like `TableViewDiffCalculator` & `CollectionViewDiffCalculator` are `final` in Dwifft but I needed them to be subclassed in RGListKit. So I had to add them as files and not dependency 👍

**Comment by riteshhgupta** [comment]
@kgn let me know if you any doubts with the library usage :)

**Comment by kgn** [comment]
@riteshhgupta I never had any doubts :) just wanted to understand how DiffKit was used in the project, if modifications were needed to it or if it could just be a dependency. Thank you!
